name: publish
on: [push]
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v2
  - name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
  - name: Build the Docker image an push it to GitHub Container Registry
run: |
  docker build . --tag ghcr.io/KristenTidmuss/DougBot:latest
  docker push ghcr.io/KristenTidmuss/DougBot:latest